services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    # hostname: ${DB_CONTAINER_NAME}
    volumes:
      - ./data/db/pgsql:/var/lib/postgresql/data
      # - ./data/db/backups:/backups
      # - ./data/db/scripts:/scripts
    ports:
      - "5432:5432"
    tmpfs:
      - /tmp
    environment:
      - POSTGRES_USER=user
      # - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=restaurant
      - PGDATA=/var/lib/postgresql/data
    # networks:
    #   - service